/** Legend entries: [Name, Short desc]. All components use the global data base ~/Fin/Data (or DATA_BASE / FIN_DATA). */
window.LEGEND_DATA = {
  alert: [
    ["received_at", "ISO timestamp when the alert was received."],
    ["text", "Raw message body; may be JSON string of the payload."],
    ["ticker", "Symbol (e.g. SPY, TQQQ)."],
    ["tf", "Timeframe (e.g. 5, D)."],
    ["date", "Session date code."],
    ["payload", "Full alert payload if parsed from text."],
    ["time", "Bar time (e.g. 2026-02-24 09:30:00 EST)."],
    ["bar_index", "Bar index within the session."],
    ["revDir", "Reversal direction: 1 = up, -1 = down, 0 = none (segment edge)."],
    ["REV_avwap", "Reversal anchor VWAP for the bar (from indicator)."],
    ["htfVwap", "Higher-timeframe VWAP (optional; from indicator)."],
    ["close", "Bar close price."],
    ["open", "Bar open price."],
    ["high", "Bar high price."],
    ["low", "Bar low price."],
    ["volume", "Bar volume."],
  ],
  raw_vector: [
    ["segment_id", "File stem: ticker_date_tf_start_end (e.g. SPY_260222_5_0935_1022)."],
    ["ticker", "Symbol."],
    ["date", "YYMMDD session date."],
    ["tf", "Timeframe (5, D, etc.)."],
    ["time", "Bar time string (e.g. 2026-02-24 09:30:00 EST)."],
    ["bar_index", "Bar index within session."],
    ["close", "Close price for the bar."],
    ["open", "Open price (if present)."],
    ["high", "High price (if present)."],
    ["low", "Low price (if present)."],
    ["volume", "Volume for the bar."],
    ["revDir", "Reversal direction (1, -1, 0)."],
    ["REV_avwap", "Reversal anchor VWAP from indicator."],
    ["htfVwap", "Higher-timeframe VWAP (optional)."],
    ["atrRatio", "ATR ratio (if present)."],
    ["tShockScoreTot", "Shock score series (if present)."],
    ["tTrendAbs", "Trend strength series (if present)."],
    ["inTrendScore", "In-trend score series (if present)."],
    ["tRegimeAbs", "Regime strength (if present)."],
    ["smaCrossScoreInd", "SMA cross score (if present)."],
    ["bars", "Number of bars in segment up to this closing bar."],
    ["slope_pctPerMin", "Slope or rate metric (if present in raw)."],
    ["atrNow", "Current ATR (if present)."],
    ["atrBase", "Base ATR (if present)."],
  ],
  classified: [
    ["segment_id", "Same as raw: ticker_date_tf_start_end."],
    ["ticker", "Symbol."],
    ["date", "YYMMDD."],
    ["tf", "Timeframe."],
    ["start_time", "Time of first bar in segment."],
    ["duration_min", "Segment length in minutes."],
    ["closing_bar_index", "Bar index (0-based) for this record."],
    ["bars", "Bars in expanding window [0..k]."],
    ["p0_close", "Close of first bar in segment."],
    ["p1_close", "Close of last bar in segment."],
    ["delta_pct", "Price change percent over the segment."],
    ["slope_pctPerMin", "Delta % per minute."],
    ["range_pct", "High-low range as % of start price."],
    ["efficiency", "|close change| / range (0–1)."],
    ["dollarVol_sum", "Sum of close×volume over segment."],
    ["vol_slope", "Linear regression slope of volume over bars."],
    ["vol_peak_ratio", "Max volume / median volume."],
    ["atrRatio_peak", "Peak ATR ratio in segment."],
    ["atrRatio_q50", "Median ATR ratio in segment."],
    ["tTrendAbs_area", "Sum of tTrendAbs over bars."],
    ["tTrendAbs_active_frac", "Fraction of bars above trend threshold."],
    ["inTrendScore_area", "Sum of inTrendScore over bars."],
    ["tRegimeAbs_active_frac", "Fraction of bars above regime threshold."],
    ["smaCrossScoreInd_active_frac", "Fraction of bars above SMA cross threshold."],
    ["tShockScoreTot_peak", "Peak shock score in segment."],
    ["tShockScoreTot_density", "Fraction of bars above shock threshold."],
    ["tShock_time_to_peak", "Normalized time to peak shock (0–1)."],
    ["rev_avwap_side_frac", "Fraction of bars with close above REV_avwap."],
    ["rev_avwap_cross_count", "Number of close/REV_avwap crosses."],
    ["rev_avwap_dist_abs_mean_pct", "Mean |close−REV_avwap|/REV_avwap as %."],
    ["htfVwap_side_frac", "Fraction of bars with close above htfVwap."],
    ["htfVwap_cross_count", "Number of close/htfVwap crosses."],
    ["profit_score", "Score for profit potential (percentile within file)."],
    ["entry_score", "Score for entry quality (percentile within file)."],
    ["maintain_score", "Score for maintain/hold (percentile within file)."],
    ["tradeability_score", "Score for tradeability (percentile within file)."],
    ["tier", "Tier from percentiles: elite, high_quality, tradable, difficult, low_edge, non_tradable."],
    ["next_profit_score", "Profit score from last bar of next segment (same ticker/date/tf)."],
    ["next_entry_score", "Entry score from next segment last bar."],
    ["next_maintain_score", "Maintain score from next segment last bar."],
    ["next_tradeability_score", "Tradeability score from next segment last bar."],
    ["next_delta_pct", "Delta % from next segment last bar."],
    ["next_tier", "Tier from next segment last bar."],
  ],
  bin: [
    ["run_split_then_classify.sh", "Single process: runs splitter (alerts -> raw_vectors) then vector_calc (raw_vectors -> classified). Uses global data base (~/Fin/Data or DATA_BASE). Param: YYMMDD (process one date) or \"all\" (default). Existing classified files are overwritten. Run from vectorGen root."],
    ["classify-vectors.sh", "Runs vector_calc to build classified vectors from raw_vectors: one JSONL per segment with expanding-window records, scoring (profit/entry/maintain/tradeability, tier), and next_* fields. Uses the global data base: reads from ~/Fin/Data/raw_vectors and writes to ~/Fin/Data/classified (override with RAW_VECTORS_DIR or args). Run from vectorGen root."],
    ["ui-server.sh", "Starts, stops, or reports status of the VectorGen UI server (Node server in ui/). Uses the global data base for classified, alerts, and trades (~/Fin/Data). Default port 8000. Run from vectorGen root; set VECTORGEN_ROOT if needed."],
    ["run_vector_calc.sh", "Invokes vector_calc (Python) from vectorGen root. Reads raw_vectors and writes classified under the global data base; use --raw-dir or RAW_VECTORS_DIR to point at ~/Fin/Data/raw_vectors. Run with --info for full usage."],
    ["run_splitter.sh", "Runs daily_alerts_splitter: reads alert JSONL files and splits them into raw_vectors by revDir segment edges. Uses the global data base: set ALERTS_DIR or --alerts-dir to the alerts folder (e.g. ~/Fin/Data/Alerts); writes raw_vectors alongside. Run from vectorGen root."],
  ],
  trade: [
    ["side", "Long or short."],
    ["entry_time", "Entry bar or timestamp."],
    ["exit_time", "Exit bar or timestamp."],
    ["entry_price", "Fill or reference price at entry."],
    ["exit_price", "Fill or reference price at exit."],
    ["pnl_pct", "Realized P&amp;L in percent."],
    ["tier", "Tier of the segment used for the trade."],
  ],
};
